# Generated by Django 5.0.3 on 2024-03-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_guest_mobile_alter_guest_name_alter_movie_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
    ]
